### ISSUE TITLE
LIF conversion errors

### ISSUE THREAD

**Issue by NicoKiaru** [BIOP/ijp-kheops#18]
java.io.FileNotFoundException: E:\out\20200929 - Panini Imaging_TileScan 4_s19.ome.tiff (The process cannot access the file because it is being used by another process)
	at java.io.RandomAccessFile.open0(Native Method)
	at java.io.RandomAccessFile.open(RandomAccessFile.java:316)
	at java.io.RandomAccessFile.<init>(RandomAccessFile.java:243)
	at loci.common.NIOFileHandle.<init>(NIOFileHandle.java:130)
	at loci.common.NIOFileHandle.<init>(NIOFileHandle.java:151)
	at loci.common.NIOFileHandle.<init>(NIOFileHandle.java:165)
	at loci.common.Location.getHandle(Location.java:522)
	at loci.common.Location.getHandle(Location.java:462)
	at loci.common.Location.getHandle(Location.java:443)
	at loci.common.RandomAccessOutputStream.<init>(RandomAccessOutputStream.java:66)
	at loci.formats.out.PyramidOMETiffWriter.close(PyramidOMETiffWriter.java:131)
	at ch.epfl.biop.kheops.ometiff.OMETiffPyramidizerExporter.export(OMETiffPyramidizerExporter.java:666)
	at ch.epfl.biop.kheops.command.KheopsCommand.lambda$run$2(KheopsCommand.java:198)
	at java.util.stream.ForEachOps$ForEachOp$OfInt.accept(ForEachOps.java:204)
	at java.util.stream.Streams$RangeIntSpliterator.forEachRemaining(Streams.java:110)
	at java.util.Spliterator$OfInt.forEachRemaining(Spliterator.java:693)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:482)
	at java.util.stream.ForEachOps$ForEachTask.compute(ForEachOps.java:290)
	at java.util.concurrent.CountedCompleter.exec(CountedCompleter.java:731)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:175)

**Comment by NicoKiaru** [comment]
Most probably it's windows which takes a handle to tiff files when the explorer is opened. Maybe the conversion should be done with files which do not have a tiff extension to prevent this issue. Then rename them at the end when they are written.

The current workaround is to avoid having a windows explorer opened to the export folder when the conversion takes place

**Comment by NicoKiaru** [comment]
There was a big discussion about preventing windows from making thumbnails or whatever, but I can't find the thread anymore.
