### ISSUE TITLE
Issue with bio-formats 7.0.1

### ISSUE THREAD

**Issue by NicoKiaru** [BIOP/ijp-kheops#23]
I get this error:
```
[ERROR] Command errored: Export Sources To OME Tiff (build pyramid)
java.lang.NoSuchFieldError: disableChromaSubsampling
	at loci.formats.codec.WrappedCodec.copyOptions(WrappedCodec.java:159)
	at loci.formats.codec.WrappedCodec.getOptions(WrappedCodec.java:193)
	at loci.formats.codec.WrappedCodec.compress(WrappedCodec.java:63)
	at loci.formats.codec.PassthroughCodec.compress(PassthroughCodec.java:44)
	at loci.formats.tiff.TiffCompression.compress(TiffCompression.java:365)
	at loci.formats.tiff.TiffSaver.writeImage(TiffSaver.java:427)
	at loci.formats.tiff.TiffSaver.writeImage(TiffSaver.java:278)
	at loci.formats.out.TiffWriter.saveBytes(TiffWriter.java:282)
	at loci.formats.out.OMETiffWriter.saveBytes(OMETiffWriter.java:219)
	at loci.formats.out.PyramidOMETiffWriter.saveBytes(PyramidOMETiffWriter.java:89)
	at loci.formats.out.OMETiffWriter.saveBytes(OMETiffWriter.java:209)
	at ch.epfl.biop.kheops.ometiff.OMETiffExporter.export(OMETiffExporter.java:586)
	at ch.epfl.biop.kheops.command.KheopsExportSourcesCommand.run(KheopsExportSourcesCommand.java:154)
	at org.scijava.command.CommandModule.run(CommandModule.java:196)
	at org.scijava.module.ModuleRunner.run(ModuleRunner.java:165)
	at org.scijava.module.ModuleRunner.call(ModuleRunner.java:125)
	at org.scijava.module.ModuleRunner.call(ModuleRunner.java:64)
	at org.scijava.thread.DefaultThreadService.lambda$wrap$2(DefaultThreadService.java:247)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:750)
```

**Comment by NicoKiaru** [comment]
Related: https://forum.image.sc/t/java-lang-nosuchfielderror-disablechromasubsampling-with-ptbiop-update-site/90061

**Comment by NicoKiaru** [comment]
This was fixed by re-building the jar with pom scijava 37.0.0. No idea why this fixed the issue though...
